FROM node:22-alpine

WORKDIR /app

ARG NEXT_PUBLIC_TRANSACTIONS_REMOTE_URL=http://127.0.0.1:3001
ENV NEXT_PUBLIC_TRANSACTIONS_REMOTE_URL=$NEXT_PUBLIC_TRANSACTIONS_REMOTE_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start"]
