services:
  transactions-remote:
    build:
      context: ./transactions-remote
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production

  shell:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_TRANSACTIONS_REMOTE_URL: http://127.0.0.1:3001
    depends_on:
      - transactions-remote
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_TRANSACTIONS_REMOTE_URL: http://127.0.0.1:3001
